// Type definitions for extended diagnostics
// Contains all struct definitions used by the extended diagnostics module.

/// Error analysis and categorization
#[ derive( Debug ) ]
pub struct ErrorAnalyzer
{
  pub( super ) error_categories : HashMap< String, ErrorCategory >,
  pub( super ) total_errors : u64,
}

/// Error category containing related errors
#[ derive( Debug, Clone ) ]
pub struct ErrorCategory
{
  #[ allow( dead_code ) ]
  pub( super ) name : String,
  pub( super ) count : u64,
  pub( super ) messages : Vec< String >,
  pub( super ) status_codes : Vec< String >,
}

/// Summary of all errors across categories
#[ derive( Debug, Clone ) ]
pub struct ErrorSummary
{
  pub( super ) total_errors : u64,
  pub( super ) most_common_category : String,
  #[ allow( dead_code ) ]
  pub( super ) categories : Vec< ( String, u64 ) >,
}

/// Diagnostics context for correlation
#[ derive( Debug, Clone, Serialize, Deserialize ) ]
pub struct DiagnosticsContext
{
  pub( super ) request_id : String,
  pub( super ) user_id : Option< String >,
  pub( super ) operation : String,
  pub( super ) model : Option< String >,
  pub( super ) timestamp : Option< String >,
}

/// Diagnostics aggregator for comprehensive reporting
#[ derive( Debug ) ]
pub struct DiagnosticsAggregator
{
  pub( super ) requests : HashMap< String, RequestMetrics >,
  #[ allow( dead_code ) ]
  pub( super ) operation_metrics : HashMap< String, OperationMetrics >,
  pub( super ) total_requests : u64,
  pub( super ) successful_requests : u64,
  pub( super ) failed_requests : u64,
  pub( super ) total_duration : Duration,
}

/// Metrics for a single request
#[ derive( Debug, Clone ) ]
#[ allow( dead_code ) ]
pub( super ) struct RequestMetrics
{
  pub( super ) id : String,
  pub( super ) operation : String,
  pub( super ) start_time : Instant,
  pub( super ) duration : Option< Duration >,
  pub( super ) success : Option< bool >,
  pub( super ) error_category : Option< String >,
}

/// Metrics for operations of a specific type
#[ derive( Debug, Clone ) ]
pub struct OperationMetrics
{
  #[ allow( dead_code ) ]
  pub( super ) name : String,
  pub( super ) total_requests : u64,
  pub( super ) successful_requests : u64,
  #[ allow( dead_code ) ]
  pub( super ) failed_requests : u64,
}

/// Summary of diagnostic information
#[ derive( Debug, Clone ) ]
pub struct DiagnosticsSummary
{
  pub( super ) total_requests : u64,
  pub( super ) successful_requests : u64,
  pub( super ) failed_requests : u64,
  pub( super ) average_duration : Duration,
}

/// Diagnostics collector integrating with CURL diagnostics
#[ derive( Debug, Clone ) ]
pub struct DiagnosticsCollector
{
  // Placeholder for collection state
}

/// Diagnostics data structure
#[ derive( Debug, Clone ) ]
pub struct DiagnosticsData
{
  pub( super ) curl_representation : Option< String >,
  pub( super ) request_size : usize,
  pub( super ) estimated_cost : Option< f64 >,
  pub( super ) request_metrics : Vec< RequestMetricData >,
}

/// Data for a request metric entry
#[ derive( Debug, Clone ) ]
#[ allow( dead_code ) ]
pub( super ) struct RequestMetricData
{
  pub( super ) request_id : String,
  pub( super ) operation : String,
  pub( super ) duration : Duration,
  pub( super ) success : bool,
}

/// Mock exporter for testing
#[ derive( Debug ) ]
pub struct DiagnosticsExporter;

/// Real-time monitoring capabilities
#[ derive( Debug ) ]
pub struct RealtimeMonitor
{
  pub( super ) alert_count : u32,
  pub( super ) latencies : Vec< Duration >,
}

/// Status information for monitoring
#[ derive( Debug ) ]
pub struct MonitoringStatus
{
  pub( super ) degraded : bool,
}

/// Load testing integration
#[ derive( Debug, Clone ) ]
pub struct LoadTester
{
  pub( super ) _collector : DiagnosticsCollector,
}

/// Results from a load test
#[ derive( Debug ) ]
pub struct LoadTestResults
{
  pub( super ) total_requests : u32,
  pub( super ) average_latency : Duration,
  pub( super ) success_rate : f64,
}

/// Alerting system
#[ derive( Debug ) ]
pub struct AlertingSystem
{
  pub( super ) _collector : DiagnosticsCollector,
  pub( super ) alerts : Vec< Alert >,
}

/// Alert generated by the monitoring system
#[ derive( Debug, Clone ) ]
pub struct Alert
{
  pub( super ) alert_type : String,
}

/// Aggregated metrics data
#[ derive( Debug ) ]
pub struct AggregatedMetrics
{
  pub( super ) request_count : u32,
  pub( super ) has_performance_data : bool,
}
